[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "alembic upgrade head && uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
